### PR TITLE
Propagate per-operation DB rollbacks up to the VM for retries

### PR DESCRIPTION
**Pull request by rdaum**
Alter error handling so that rollbacks inside WorldState operations are caught and propagated up so that the VM can rollback-retry operations on failures.

This is because WiredTiger in particular can return Rollback for conflicts even before `commit` is attempted.

### CODE REVIEW

**Comment by abesto** [comment]
Aww, I kinda liked `wildtiger`!

(Will actually review tonight)

**Review by nnunley — APPROVED** [review]
LGTM. IT's too bad that MOO semantics requires we loose the messages associated with the various error codes.

**Comment by rdaum** [comment]
> LGTM. IT's too bad that MOO semantics requires we loose the messages associated with the various error codes.

Actually MOO does support this... kind-of... the `raise` function can take arguments with optional message and optional value.

Just modified the MR to fix the missing support for that.

I suspect there's other places in MOO where that message and value can be set, I just don't know them yet.

**Review by abesto — APPROVED** [review]
Well I haven't picked up most of the context to understand the meat of this (and today is not the day I will because I'm very out of brain). But: nothing stands out as weird or wrong, the words make sense, and the code seems to do what the words say! :D

**Pull request merged**
